version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myadmin1
      POSTGRES_PASSWORD: P@ssw0rd!!!
      POSTGRES_DB: voice
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
